# Generated by Django 5.2.6 on 2026-05-20 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('md5_hash', models.CharField(max_length=64, unique=True, verbose_name='MD5哈希')),
                ('filename', models.CharField(max_length=512, verbose_name='文件名')),
                ('file_path', models.CharField(max_length=1024, verbose_name='文件路径')),
                ('file_size', models.BigIntegerField(default=0, verbose_name='文件大小(字节)')),
                ('file_type', models.CharField(max_length=20, verbose_name='文件类型')),
                ('chunk_count', models.IntegerField(default=0, verbose_name='文档块数量')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='上传时间')),
            ],
            options={
                'verbose_name': '知识库文档',
                'verbose_name_plural': '知识库文档',
                'db_table': 'knowledge_documents',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
